// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Reveal from 'stimulus-reveal-controller'
import Notification from 'stimulus-notification'

application.register('reveal', Reveal)
application.register('notification', Notification)
